import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const modulePath=process.argv[2]??'target/multitrack-example/multitrack_wasm.js';
const root=process.argv[3]??'.';
const wasm=await import(pathToFileURL(path.resolve(modulePath)));
await wasm.default({module_or_path:await fs.readFile(modulePath.replace(/\.js$/,'_bg.wasm'))});
const folder=path.join(root,'tests/fixtures/packed_aac/clear'),resources={};
for(const file of await fs.readdir(folder))if(file.endsWith('.bin'))resources['https://example.test/'+file]=new Uint8Array(await fs.readFile(path.join(folder,file)));
const recorder=new wasm.MultiRecorder(resources,JSON.stringify(['en','ja']),true);
const text=await fs.readFile(path.join(folder,'input.m3u8'),'utf8');
for(const id of ['primary','en','ja'])await recorder.accept(id,text,'https://example.test/input.m3u8','9007199254740993');
recorder.cues(JSON.stringify([{generation:'0',epoch:'0',start:{ticks:'0',timescale:1000},end:{ticks:'1000',timescale:1000},identifier:'demo',payload:'caption',settings:'align:start'}]));
recorder.end_subtitles();
let size=0,calls=0;
const sink=new WritableStream({async write(bytes){calls++;size+=bytes.length;await new Promise(r=>setTimeout(r,0));}}).getWriter();
const report=JSON.parse(await recorder.run(bytes=>sink.write(bytes)));await sink.close();
if(report.tracks.length!==4||BigInt(report.media.bytes_written)!==BigInt(size)||calls<2||report.subtitle_reports.length===0)throw new Error('multitrack example failed');
recorder.free();console.log(JSON.stringify({status:'PASS',tracks:report.tracks.length,bytes:size,writes:calls}));
